### ISSUE TITLE
repository not up-to-date with published pypi package

### ISSUE THREAD

**Issue by smarek** [surajForDD/AttachmentsExtractor#2]
Hey, thanks, i've just tried, and your current implementation works great for me

I've thought about contributing script (that would pip/python setup.py install) provide for simple usage, however I'm unsure how the current codebase maps to releases

Branch **version1** has no tags and [setup.py](https://github.com/surajForDD/AttachmentsExtractor/blob/version1/setup.py) descriptors do not match whats on https://pypi.org/project/AttachmentsExtractor/ 

Could you please push latest code and tag the 1.0.2 version in repository? I'll then happily help you with some helper script, that provides console guidance (arguments validation and usage/help)

**Comment by surajForDD** [comment]
Hi i have updated the latest code in master. feel free to create changes and raise a PR.
