### ISSUE TITLE
BadZipFile error when processing a lot of file. 

### ISSUE THREAD

**Issue by Laxmi530** [surajForDD/AttachmentsExtractor#4]
Hai,
I have tried to check a bunch of .docx file that contain attachment or not but I am getting the error. Can someone please help me. 
I have attached the screen shots.

![image](https://user-images.githubusercontent.com/76505459/174774309-a2594824-8c56-41dd-a888-3673632355dd.png)

![image](https://user-images.githubusercontent.com/76505459/174774431-33131058-4b9d-4545-bfc9-2e083abc6c46.png)

**Comment by surajForDD** [comment]
The Code you are using is sending relative paths to the function try sending absolute path it should work.
