### ISSUE TITLE
Embedded .xlsx files are extracted, but are corrupted

### ISSUE THREAD

**Issue by RamakanthSharma** [surajForDD/AttachmentsExtractor#6]
The extracted .xlsx files do not open. Looks like they are corrupted. What is the solution?

**Comment by surajForDD** [comment]
Hi thanks for reporting this issue. When i had a look at  the extracted .xlsx files they  are not corrupted but seem  to have the property of the workbookView set to be hidden on the extracted .xlsx file, which if you try to open with excel shows something like below 

![image](https://github.com/surajForDD/AttachmentsExtractor/assets/53933384/6e20fd28-7b0e-4053-9a26-7caf3696811e)

if you want to view the contents you can click on View -> Unhide and click on Ok 



if you want to achieve the same programmatically you can do so with the following piece of code after extracting the documents. 

` import openpyxl



workbook = openpyxl.open("path_to_excel")

for view in workbook.views: 
    view.visibility="visible"
workbook.save("path_to_new_excel") `

**Comment by RamakanthSharma** [comment]
Thank you for your quick response. 

Used win32com library to unhide the file programmatically and it works absolutely fine now.

Thank you for your help. Appreciate it!
